name: Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  DeployProduction:
    name: "Deploy: Production"
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        app:
        - { path: "./dist", cloudflareName: "nullvoxpopuli-dot-com", name: "docs" }


    permissions:
      contents: read
      deployments: write

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build
      - run: pnpm ember build --environment production
      - name: Publish ${{ matrix.app.id }}
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.app.cloudflareName }}
          directory: ${{ matrix.app.path }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}


